"""add orig_paint_date

Revision ID: 35dbefcf3d1c
Revises: 8112fdf48d1c
Create Date: 2020-07-20 18:53:04.003649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy.ext.declarative import declarative_base

# revision identifiers, used by Alembic.
revision = '35dbefcf3d1c'
down_revision = '8112fdf48d1c'
branch_labels = None
depends_on = None

Base = declarative_base()

class Room(Base):
    __tablename__ = 'room'
    
    id = sa.Column(sa.Integer, primary_key=True)
    orig_paint_date = sa.Column(sa.DateTime)
    date_last_paint = sa.Column(sa.DateTime)



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('orig_paint_date', sa.DateTime(), nullable=True))


    ####
    # Here is where you can connect your declarative model to the database going through the migration    
    bind = op.get_bind() 
    session = orm.Session(bind=bind)
    # now that we've got a session

    for rm in session.query(Room):
        rm.orig_paint_date = rm.date_last_paint
        session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'orig_paint_date')
    # ### end Alembic commands ###
