"""empty message

Revision ID: 3de98a14cbf8
Revises: c3a8c7e3598d
Create Date: 2020-06-13 13:32:41.733164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de98a14cbf8'
down_revision = 'c3a8c7e3598d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isEmployed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isEmployed')
    # ### end Alembic commands ###
