"""empty message

Revision ID: 5a74e1d06d38
Revises: 02cb5d6bcdfa
Create Date: 2021-01-22 12:36:48.857665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a74e1d06d38'
down_revision = '02cb5d6bcdfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'glaccount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('glaccount', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
