"""empty message

Revision ID: 8112fdf48d1c
Revises: 3de98a14cbf8
Create Date: 2020-07-16 16:25:10.181498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table

# revision identifiers, used by Alembic.
revision = '8112fdf48d1c'
down_revision = '3de98a14cbf8'
branch_labels = None
depends_on = None

adminUsernames = (
    "Admin",
    "SteveY",
)

managerUsernames = (
    "RussW",
    "ChrisL"
)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_level', sa.Integer(), nullable=False, server_default='1'))


    # in order for a data migration to work, 
    # you need to define the tables and fields within those tables inside the migration script. 
    user = table(
        'user',
        sa.Column('username', sa.String(20)),
        sa.Column('access_level', sa.Integer)
        # Other columns not needed for this data migration
    )
    # Set everyone to access_level 1
    op.execute(
        user
            .update()
            .values({'access_level':1})
    )
    # Set admins to 7
    op.execute(
        user
            .update()
            .where(user.c.username.in_(adminUsernames))
            .values({'access_level':7})
    )
    # Set managers to 5
    op.execute(
        user
            .update()
            .where(user.c.username.in_(managerUsernames))
            .values({'access_level':5})
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_level')
    # ### end Alembic commands ###
