"""Added clientPhonenumber

Revision ID: c3a8c7e3598d
Revises: d1904e22a44d
Create Date: 2020-06-12 15:40:02.439824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a8c7e3598d'
down_revision = 'd1904e22a44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('contactPhone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'contactPhone')
    # ### end Alembic commands ###
