"""Added Client Table

Revision ID: d1904e22a44d
Revises: 02e2d3f5fd02
Create Date: 2020-06-12 15:06:18.483451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1904e22a44d'
down_revision = '02e2d3f5fd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contactName', sa.String(length=50), nullable=True),
    sa.Column('contactEmail', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contactEmail'),
    sa.UniqueConstraint('name')
    )
    op.add_column('project', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'client_id')
    op.drop_table('client')
    # ### end Alembic commands ###
