"""Initial Migration

Revision ID: fab33cec10c4
Revises: 
Create Date: 2020-12-03 16:58:59.879174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab33cec10c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contactName', sa.String(length=50), nullable=True),
    sa.Column('contactEmail', sa.String(length=50), nullable=True),
    sa.Column('contactPhone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contactEmail'),
    sa.UniqueConstraint('name')
    )
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('addr_str', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('addr_str', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fName', sa.String(length=30), nullable=False),
    sa.Column('lName', sa.String(length=30), nullable=False),
    sa.Column('cellPhone', sa.String(length=20), nullable=True),
    sa.Column('image_file', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('isEmployed', sa.Boolean(), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('worktype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('descriptor', sa.Text(), nullable=True),
    sa.Column('color_sheet', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('typeOfWork_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_finished', sa.DateTime(), nullable=True),
    sa.Column('target_end_date', sa.DateTime(), nullable=True),
    sa.Column('hours_estimate', sa.Float(), nullable=True),
    sa.Column('quote_amt', sa.Float(), nullable=True),
    sa.Column('invoice_amt', sa.Float(), nullable=True),
    sa.Column('labour', sa.Float(), nullable=True),
    sa.Column('materials', sa.Float(), nullable=True),
    sa.Column('damage_comment', sa.String(length=500), nullable=True),
    sa.Column('extenuating_circumstances', sa.String(length=500), nullable=True),
    sa.Column('purchase_order', sa.String(length=50), nullable=True),
    sa.Column('work_order', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['typeOfWork_id'], ['worktype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('date_uploaded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_area',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'area_id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bm_id', sa.String(length=25), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('orig_paint_date', sa.DateTime(), nullable=True),
    sa.Column('date_last_paint', sa.DateTime(), nullable=True),
    sa.Column('freq', sa.Integer(), nullable=True),
    sa.Column('date_next_paint', sa.DateTime(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('glaccount', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timesheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_of_work', sa.Date(), nullable=False),
    sa.Column('date_submit', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sheen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sheen_id'], ['sheen.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_room',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'room_id')
    )
    op.create_table('project_timesheet',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('timesheet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheet.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'timesheet_id')
    )
    op.create_table('user_timesheet',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timesheet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'timesheet_id')
    )
    op.create_table('paint_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paint_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('prod_code', sa.String(length=15), nullable=True),
    sa.Column('base', sa.String(length=15), nullable=True),
    sa.Column('formula', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['paint_id'], ['paint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paint_color')
    op.drop_table('user_timesheet')
    op.drop_table('project_timesheet')
    op.drop_table('project_room')
    op.drop_table('paint')
    op.drop_table('timesheet')
    op.drop_table('room')
    op.drop_table('project_area')
    op.drop_table('product')
    op.drop_table('color_sheet')
    op.drop_table('project')
    op.drop_table('post')
    op.drop_table('brand')
    op.drop_table('area')
    op.drop_table('worktype')
    op.drop_table('user')
    op.drop_table('supplier')
    op.drop_table('status')
    op.drop_table('site')
    op.drop_table('sheen')
    op.drop_table('color')
    op.drop_table('client')
    # ### end Alembic commands ###
